# Generated by Django 3.1.7 on 2021-03-15 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0003_auto_20210315_0405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtuber',
            old_name='name',
            new_name='nme',
        ),
    ]
