# Generated by Django 3.1.7 on 2021-03-15 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0004_auto_20210315_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Youtuber',
        ),
    ]
