# Generated by Django 3.1.7 on 2021-03-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0006_youtuber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
