# Generated by Django 3.1.7 on 2021-03-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0007_auto_20210315_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='description',
            field=models.TextField(),
        ),
    ]
