# Generated by Django 3.1.7 on 2021-03-15 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0009_auto_20210315_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
