# Generated by Django 3.1.7 on 2021-03-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0011_auto_20210315_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtuber',
            old_name='its_feature',
            new_name='is_featured',
        ),
    ]
